{
 "title": "应用程序监控",
 "time": { "from": "2021-11-30T04:50:30.374Z", "to": "2021-11-30T05:50:30.374Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{}, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(kube_service_info{namespace=\"$namespace\"},service)"
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "http error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(monitor_server_handler_counter{namespace=\"$namespace\",service=\"$service\",type=\"http\",code!=\"200\"}[$interval])) by (code,api)"
    }
   ]
  },
  {
   "title": "p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90,rate(monitor_server_handle_histogram_bucket{namespace=\"$namespace\",service=\"$service\"}[$interval])) * 1000) by (api,method)"
    }
   ]
  },
  {
   "title": "http qps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(monitor_server_handler_counter{namespace=\"$namespace\",service=\"$service\",type=\"http\"}[$interval])) by (api,method)"
    }
   ]
  }
 ]
}