apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micrometer-demo
  labels:
    release: prometheus
spec:
  endpoints:
    - port: postserver
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      svc: postserver